import requests
import smtplib
import datetime

LATITUDE="Your Location LATITUDE"
LONGITUDE="Your Location LONGITUDE"

def is_iss_overhead():
    response = requests.get("http://api.open-notify.org/iss-now.json")
    response.raise_for_status()
    data = response.json()
    iss_latitude = float(data["iss_position"]["latitude"])
    iss_longitude = float(data["iss_position"]["longitude"])
    print("ISS Latitude:", iss_latitude )
    print("ISS Longitude:", iss_longitude )

    # If iss latitude and longitude are in range of 5 degree then you should notify by email

    if (LATITUDE -5 <= iss_latitude <= LATITUDE + 5) and (LONGITUDE - 5 <= iss_longitude <= LONGITUDE+5):
        return True
    
    


def is_night():
    parameters ={
        "lat":LATITUDE,
        "lng" :LONGITUDE,
        "formatted":0
    }

    response = requests.get(f"https://api.sunrise-sunset.org/json", params=parameters)
    response.raise_for_status()
    data = response.json()
    sunrise = int(data["results"]["sunrise"].split("T")[1].split(":")[0])
    sunset = int(data["results"]["sunset"].split("T")[1].split(":")[0])


    time_now = datetime.datetime.now().hour
    if time_now >= sunset or time_now <= sunrise:
        return True

print(is_night())

if is_iss_overhead() and is_night():
    email = "Enter Your Email"
    pass_key = "Enter App Password generated by gmail"
    connection = smtplib.SMTP("Your mail provider SMTP")

    connection.starttls()
    connection.login(user=email, password=pass_key)
    connection.sendmail(from_addr=email, to_addrs="your email address for notification", msg="Subject:ISS Location Alert\n\nISS is nearby and its night time if sky is clear You can look up to watch ISS.")
    connection.close()
